
image: node:10.15.3


clone:
  depth: full        

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - sonar
        script:
         # Build your project and run
          - pipe: sonarsource/sonarcloud-scan:1.2.1

pipelines:                
  branches:
    develop:
      - step: *build-test-sonarcloud
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
